"""
export_utils.py
Generate PDF and Word documents from AI Math Tutor solutions.
"""

import os
import logging
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT

from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

logger = logging.getLogger(__name__)

EXPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "exports")
os.makedirs(EXPORTS_DIR, exist_ok=True)


def _timestamp_name(prefix: str, ext: str) -> str:
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    return os.path.join(EXPORTS_DIR, f"{prefix}_{ts}.{ext}")


# ── PDF Export ────────────────────────────────────────────────────────────────

def export_to_pdf(data: dict) -> str:
    """
    Generate a formatted PDF from solution data.
    data keys: equation, latex_equation, steps, solution, mistakes
    Returns: absolute path to generated PDF.
    """
    filepath = _timestamp_name("math_solution", "pdf")
    doc = SimpleDocTemplate(filepath, pagesize=A4,
                             leftMargin=2*cm, rightMargin=2*cm,
                             topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Title"],
                                  fontSize=18, textColor=colors.HexColor("#1a73e8"),
                                  spaceAfter=12, alignment=TA_CENTER)
    heading_style = ParagraphStyle("Heading", parent=styles["Heading2"],
                                    fontSize=13, textColor=colors.HexColor("#333333"),
                                    spaceBefore=10, spaceAfter=6)
    body_style = ParagraphStyle("Body", parent=styles["Normal"],
                                  fontSize=11, leading=16, spaceAfter=4)
    step_style = ParagraphStyle("Step", parent=styles["Normal"],
                                  fontSize=11, leading=16,
                                  leftIndent=20, spaceAfter=4,
                                  textColor=colors.HexColor("#444444"))
    warning_style = ParagraphStyle("Warning", parent=styles["Normal"],
                                     fontSize=11, textColor=colors.HexColor("#c0392b"),
                                     leftIndent=20, spaceAfter=4)

    story = []

    # Title
    story.append(Paragraph("AI Math Tutor — Solution Report", title_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dddddd")))
    story.append(Spacer(1, 0.3*cm))

    # Equation
    story.append(Paragraph("Problem", heading_style))
    story.append(Paragraph(f"<b>Equation:</b> {data.get('equation', 'N/A')}", body_style))
    story.append(Spacer(1, 0.3*cm))

    # Steps
    steps = data.get("steps", [])
    if steps:
        story.append(Paragraph("Step-by-Step Solution", heading_style))
        for s in steps:
            story.append(Paragraph(
                f"<b>Step {s['step']}:</b> {s['description']}", step_style))
            story.append(Paragraph(f"&nbsp;&nbsp;{s['expression']}", step_style))
        story.append(Spacer(1, 0.3*cm))

    # Final answer
    solution = data.get("solution", [])
    if solution:
        story.append(Paragraph("Final Answer", heading_style))
        ans = ", ".join(str(s) for s in solution)
        story.append(Paragraph(f"<b>x = {ans}</b>", body_style))
        story.append(Spacer(1, 0.3*cm))

    # Mistakes
    mistakes = data.get("mistakes", [])
    if mistakes:
        story.append(Paragraph("Detected Mistakes", heading_style))
        for m in mistakes:
            story.append(Paragraph(f"⚠ <b>{m['name']}</b>: {m['description']}", warning_style))
            story.append(Paragraph(f"  Hint: {m['hint']}", step_style))

    # Footer
    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    story.append(Paragraph(f"Generated by AI Math Tutor on {ts}", body_style))

    doc.build(story)
    logger.info("PDF exported: %s", filepath)
    return filepath


# ── Word Export ───────────────────────────────────────────────────────────────

def export_to_word(data: dict) -> str:
    """
    Generate a formatted .docx from solution data.
    Returns: absolute path to generated Word document.
    """
    filepath = _timestamp_name("math_solution", "docx")
    doc = Document()

    # Title
    title = doc.add_heading("AI Math Tutor — Solution Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.runs[0].font.color.rgb = RGBColor(0x1a, 0x73, 0xe8)

    doc.add_paragraph()

    # Problem
    doc.add_heading("Problem", level=2)
    p = doc.add_paragraph()
    p.add_run("Equation: ").bold = True
    p.add_run(data.get("equation", "N/A"))

    # Steps
    steps = data.get("steps", [])
    if steps:
        doc.add_heading("Step-by-Step Solution", level=2)
        for s in steps:
            p = doc.add_paragraph(style="List Number")
            run = p.add_run(f"Step {s['step']}: {s['description']}")
            run.bold = True
            doc.add_paragraph(s["expression"], style="Normal")

    # Final answer
    solution = data.get("solution", [])
    if solution:
        doc.add_heading("Final Answer", level=2)
        ans = doc.add_paragraph()
        run = ans.add_run("x = " + ", ".join(str(s) for s in solution))
        run.bold = True
        run.font.size = Pt(14)
        run.font.color.rgb = RGBColor(0x1a, 0x73, 0xe8)

    # Mistakes
    mistakes = data.get("mistakes", [])
    if mistakes:
        doc.add_heading("Detected Mistakes", level=2)
        for m in mistakes:
            p = doc.add_paragraph()
            r = p.add_run(f"⚠ {m['name']}: ")
            r.bold = True
            r.font.color.rgb = RGBColor(0xc0, 0x39, 0x2b)
            p.add_run(m["description"])
            hint_p = doc.add_paragraph(f"Hint: {m['hint']}")
            hint_p.paragraph_format.left_indent = Inches(0.3)

    # Footer
    doc.add_paragraph()
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    footer = doc.add_paragraph(f"Generated by AI Math Tutor on {ts}")
    footer.runs[0].font.size = Pt(9)
    footer.runs[0].font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    doc.save(filepath)
    logger.info("Word doc exported: %s", filepath)
    return filepath
